# Generated by Django 4.2 on 2023-05-18 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followerfollowing',
            name='follower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followings', to='profiles.profile'),
        ),
        migrations.AlterField(
            model_name='followerfollowing',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to='profiles.profile'),
        ),
    ]
