# Generated by Django 4.2 on 2023-05-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_alter_photo_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.TextField(default='comment', max_length=300, verbose_name='Comment'),
            preserve_default=False,
        ),
    ]
